name: voo_telemetry
description: OpenTelemetry integration for VooFlutter with support for traces, metrics, and logs.
version: 0.2.2
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_telemetry
topics:
  - flutter
  - opentelemetry
  - observability
  - tracing
  - otlp

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  voo_core: ^0.4.2
  http: ^1.2.0
  dio: ^5.2.0
  uuid: ^4.0.0
  collection: ^1.18.0
  synchronized: ^3.3.0+3
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  path: ^1.9.1
  fixnum: ^1.1.0
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
