name: VooFlutter
packages:
  - apps/*
  - packages/*
  - tools/*

scripts:
  prepare_logging:
    description: Prepare the voo_logging_devtools_extension package by fetching dependencies.
    run: melos exec --scope voo_logging_devtools_extension -- dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_logging/extension/devtools

  validate_logging:
    description: Validate the voo_logging_devtools_extension package.
    run: melos exec --scope voo_logging_devtools_extension -- dart run devtools_extensions validate --package=../../packages/voo_logging
