name: VooFlutter
packages:
  - apps/*
  - packages/*
  - tools/*

scripts:
  get:
    description: Get dependencies for all packages.
    run: melos bootstrap

  clean:
    description: Clean all packages.
    run: melos clean

  # Core package commands
  prepare_devtools:
    description: Prepare the voo_devtools_extension package by fetching dependencies.
    run: melos exec --scope voo_devtools_extension -- dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_core/extension/devtools

  validate_devtools:
    description: Validate the voo_devtools_extension package.
    run: melos exec --scope voo_devtools_extension -- dart run devtools_extensions validate --package=../../packages/voo_core

  build_devtools_extension:
    description: Build the voo DevTools extension.
    run: melos exec --scope voo_devtools_extension -- dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_core/extension/devtools

  # Publishing commands for each package
  publish_core:
    description: Build and publish the voo_core package (requires manual confirmation).
    run: |
      melos run build_devtools_extension
      echo "================================================"
      echo "Build complete! Now run the following command:"
      echo "cd packages/voo_core && dart pub publish"
      echo "================================================"

  publish_logging:
    description: Publish the voo_logging package (requires manual confirmation).
    run: |
      echo "================================================"
      echo "Run the following command:"
      echo "cd packages/voo_logging && dart pub publish"
      echo "================================================"

  publish_analytics:
    description: Publish the voo_analytics package (requires manual confirmation).
    run: |
      echo "================================================"
      echo "Run the following command:"
      echo "cd packages/voo_analytics && dart pub publish"
      echo "================================================"

  publish_performance:
    description: Publish the voo_performance package (requires manual confirmation).
    run: |
      echo "================================================"
      echo "Run the following command:"
      echo "cd packages/voo_performance && dart pub publish"
      echo "================================================"

  # Test commands
  test_all:
    description: Run tests for all packages.
    run: melos run test --no-select

  test:
    description: Run tests for selected packages.
    run: melos exec -- flutter test

  # Build runner commands
  build_runner_all:
    description: Run build_runner for all packages that need it.
    run: melos exec --depends-on="build_runner" -- dart run build_runner build --delete-conflicting-outputs

  # Analyze
  analyze:
    description: Analyze all packages.
    run: melos exec -- dart analyze
