name: VooFlutter
packages:
  - apps/*
  - packages/*
  - tools/*

scripts:
  prepare_logging:
    description: Prepare the voo_logging_devtools_extension package by fetching dependencies.
    run: melos exec --scope voo_logging_devtools_extension -- dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_logging/extension/devtools

  validate_logging:
    description: Validate the voo_logging_devtools_extension package.
    run: melos exec --scope voo_logging_devtools_extension -- dart run devtools_extensions validate --package=../../packages/voo_logging

  build_logging_extension:
    description: Build the voo_logging DevTools extension.
    run: melos exec --scope voo_logging_devtools_extension -- dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_logging/extension/devtools

  publish_logging:
    description: Build and publish the voo_logging package (requires manual confirmation).
    run: |
      melos run build_logging_extension
      echo "================================================"
      echo "Build complete! Now run the following command:"
      echo "cd packages/voo_logging && dart pub publish"
      echo "================================================"
      echo "Note: Publishing requires manual confirmation and cannot be automated through melos."
