name: VooFlutter
packages:
  - apps/*
  - packages/*
  - tools/*

command:
  version:
    # Generate a workspace-level changelog
    workspaceChangelog: true

    # Restrict versioning to main branch only
    branch: main

    # Update dependent packages automatically
    updateGitTagRefs: true # Update git tag references in pubspec.yaml

    # Commit message template for version updates
    message: |
      chore(release): publish packages

      {new_package_versions}

    # Configure hooks for custom actions during versioning
    hooks:
      preCommit: |
        # Run tests before committing version changes
        melos run test_all
        # Update example app dependencies
        cd apps/voo_example && flutter pub get

scripts:
  # Version management commands
  version:
    description: Version packages using conventional commits.
    run: melos version

  version_prerelease:
    description: Create prerelease versions for packages with changes.
    run: melos version --prerelease

  version_graduate:
    description: Graduate prerelease packages to stable versions.
    run: melos version --graduate

  version_check:
    description: Check which packages would be versioned without making changes.
    run: melos version --no-git-tag-version --no-git-commit-version

  changelog:
    description: Generate changelogs without versioning.
    run: melos version --no-git-tag-version --yes

  get:
    description: Get dependencies for all packages.
    run: melos bootstrap

  clean:
    description: Clean all packages.
    run: melos clean

  build_devtools_extension:
    description: Build DevTools extensions for all packages.
    run: |
      cd tools/voo_devtools_extension && flutter pub get && \
      dart run devtools_extensions build_and_copy --source=. --dest=../../packages/voo_core/extension/devtools
  # Test commands
  test_all:
    description: Run tests for all packages.
    run: melos run test --no-select

  test:
    description: Run tests for selected packages.
    run: melos exec -- flutter test

  widget_preview:
    packageFilters:
      scope: voo_ui
    description: Run widget previews for selected packages.
    run: flutter widget-preview start
