name: voo_toast_example
description: Example application for VooToast package
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_toast:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
