name: voo_core
description: "[DEPRECATED] Use voo_telemetry instead. Core foundation package for the Voo Flutter ecosystem."
version: 2.0.0
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_core

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  vm_service: ^15.0.0
  http: ^1.2.0
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

devtools_extension:
  path: extension/devtools
