name: voo_core
description: Core foundation package for the Voo Flutter ecosystem.
version: 0.0.2
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_core

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_extensions: ^0.4.0
  vm_service: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

devtools_extension:
  path: extension/devtools
