name: voo_performance
description: "Local performance monitoring toolkit for Flutter apps with network metrics and trace tracking."
version: 0.4.0
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_performance
issue_tracker: https://github.com/voostack/voo_flutter/issues
documentation: https://voostack.com/docs/performance

topics:
  - flutter
  - performance
  - monitoring
  - apm
  - profiling

funding:
  - https://github.com/sponsors/voostack
  - https://voostack.com/support

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core:
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.4.14
  test: ^1.24.0

flutter:
  uses-material-design: true
