name: voo_core
description: 'Core foundation package for the Voo Flutter ecosystem. Provides plugin architecture and shared utilities.'
version: 0.4.2
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_core
topics:
  - flutter
  - core
  - plugins
  - architecture
  - utilities

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

devtools_extension:
  path: extension/devtools
