name: voo_analytics
description: "[DEPRECATED] Use voo_telemetry instead. Analytics and heat map tracking package for Flutter applications."
version: 2.0.0
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_analytics

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core:
  voo_logging:
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.4.14
  test: ^1.24.0

flutter:
  uses-material-design: true
