name: voo_lists
description: A comprehensive collection of customizable list widgets for Flutter applications, including nested lists, reorderable lists, and grouped lists.
version: 0.1.1
homepage: https://github.com/voostack/voo_flutter
repository: https://github.com/voostack/voo_flutter/tree/main/packages/ui/voo_lists
publish_to: none
resolution: workspace

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core: ^0.4.3
  voo_responsive: ^0.1.4
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  collection: ^1.17.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
