name: voo_responsive
description: A comprehensive responsive design system for Flutter applications, providing breakpoints, responsive builders, and adaptive layouts.
version: 0.1.0
homepage: https://github.com/voostack/voo_flutter
repository: https://github.com/voostack/voo_flutter/tree/main/packages/ui/voo_responsive
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core:
    path: ../../dev/voo_core
  equatable: ^2.0.5
  flutter_bloc: ^8.1.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true