name: voo_example
description: 'An example app demonstrating all VooFlutter packages working together'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  voo_core: ^0.4.1
  voo_logging: ^0.4.2
  voo_analytics: ^0.3.0
  voo_performance: ^0.3.0
  voo_telemetry: ^0.1.0
  voo_ui_core: ^0.1.1
  voo_data_grid: ^0.7.5
  voo_calendar:
    path: ../../packages/ui/voo_calendar

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0

  dio: ^5.2.0

  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  test: ^1.25.2
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - .env
