name: voo_tokens_example
description: Example app demonstrating voo_tokens usage
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_tokens:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
