name: voo_logging
description: 'Comprehensive local logging package for Flutter applications with persistent storage and DevTools integration.'
version: 0.4.4
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_logging
topics:
  - flutter
  - logging
  - logs
  - debugging
  - devtools
resolution: workspace

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core: ^0.4.3
  voo_toast: ^0.0.6
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.7
  build_runner: ^2.4.0
  dio: ^5.0.0

flutter:
  uses-material-design: true
