name: voo_navigation
description: A comprehensive, adaptive navigation package for Flutter that automatically adjusts to different screen sizes and platforms with Material 3 design.
version: 0.0.2
homepage: https://github.com/VooFlutter/voo_navigation

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Material Design
  material_design_icons_flutter: ^7.0.7296

  # UI Core
  voo_ui_core:

  # Animations
  voo_motion:

  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Utilities
  collection: ^1.18.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
