name: voo_performance
description: High-performance monitoring, profiling, and optimization toolkit for Flutter apps with real-time metrics, frame rendering analysis, memory tracking, DevTools integration, and production-ready performance diagnostics.
version: 0.1.0
homepage: https://voostack.com
repository: https://github.com/voostack/voo_flutter/tree/main/packages/voo_performance
issue_tracker: https://github.com/voostack/voo_flutter/issues
documentation: https://voostack.com/docs/performance

topics:
  - performance
  - monitoring
  - profiling
  - optimization
  - devtools

funding:
  - https://github.com/sponsors/voostack
  - https://voostack.com/support

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  voo_core:
  voo_logging:
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.10.0
  build_runner: ^2.4.14
  test: ^1.24.0

flutter:
  uses-material-design: true
