name: voo_toast
description: A super developer-friendly toast notification package for Flutter with global access, extensive customizations, and responsive platform-specific defaults.
version: 0.0.6
homepage: https://github.com/VooStack/VooFlutter
repository: https://github.com/VooStack/VooFlutter/tree/main/packages/ui/voo_toast
topics:
  - flutter
  - toast
  - notifications
resolution: workspace

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_hooks: ^0.20.5
  collection: ^1.18.0
  rxdart: ^0.28.0
  voo_ui_core: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
