name: voo_ui
description: A comprehensive Flutter UI component library with Material 3 design, atomic pattern architecture.
version: 0.1.2
homepage: https://github.com/vooflutter/voo_ui
repository: https://github.com/vooflutter/voo_ui
issue_tracker: https://github.com/vooflutter/voo_ui/issues
documentation: https://github.com/vooflutter/voo_ui/blob/main/README.md

funding:
  - https://github.com/sponsors/vooflutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - user-interface
  - material-design
  - material3
  - data-grid
  - design-system

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
